services:
  virtualis-congress-v3-db:
    build: ./database
    ports:
      - 8080:8080
    volumes:
      - ./database/:/db/
    restart: always

  virtualis-congress-v3-dev:
    image: oven/bun
    working_dir: /usr/src/app
    volumes:
      - ./application/:/usr/src/app/
    command: bun run dev
    ports:
     - 3000:3000
    restart: always