services:
  virtualis-congress-v3-db:
    build: ./database
    ports:
      - 8080:8080
    volumes:
      - ./database/:/db/
    networks:
      - proxynetwork

  virtualis-congress-v3-dev:
    image: oven/bun:alpine
    working_dir: /usr/src/app
    volumes:
      - ./application/:/usr/src/app/
    command: bun run dev
    networks:
      - proxynetwork
    ports:
     - 3000:3000


networks:
  proxynetwork:
    external: true