services:
  virtualis-congress-v3-db-dev:
    build:
      context: ./database
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - 8080:8080
    volumes:
      - ./database/:/db/
    restart: always

  virtualis-congress-v3-dev:
    image: node:lts
    working_dir: /usr/src/app
    volumes:
      - ./application/:/usr/src/app/
    command: npm run dev
    ports:
     - 3000:3000
    restart: always