services:
  virtualis-congress-v3-db:
    build: ./database
    ports:
      - 8080:8080
    volumes:
      - ./database/:/db/

  virtualis-congress-v3-dev:
    image: oven/bun:alpine
    working_dir: /usr/src/app
    volumes:
      - ./application/:/usr/src/app/
    command: bun run dev
    networks:
      - proxynetwork
    ports:
     - 3000:3000
    depends_on:
      llmed-ehr-db:
        condition: service_healthy


networks:
  proxynetwork:
    external: true

volumes:
  llmed-ehr-db-data: